Feature
magelick/AutoSalon-trainee- pull request #1
Opened 2024-03-22 14:18 UTC by magelick

Инициализировал проект, создал приложения api (для апишки) и users (для пользователей и их последующей авторизацией через JWT). 

Далее прописал модели для БД:
1. AutoSalon (модель автосалона);
2. Сar (модель автомобиля);
3. OptionCar (модель характеристик автомобиля);
4. Supplier (модель поставщика);
5. Сustomer (модель покупателя (пользователя), которая в последующем будет использовататься для авторизации на JWT);
6. SaleHistory (модель истории продаж между автосалоном и поставщиком);
7. SpecialOfferOfAutoSalon (моедль акции для автосалона);
8. SpecialOfferOfSupplier (модель акции для поставщика);
9. SaleHistoryOfCustomer (модель истории продаж для покупателя)ж

2024-03-22 17:33 UTC, ZubritskiyAlex requested changes

2024-03-22 17:33 UTC, ZubritskiyAlex commented on autosalon/users/models.py
> +    username = models.CharField(
Здесь можно использовать enum или textchoice

2024-03-22 17:33 UTC, ZubritskiyAlex commented on autosalon/users/models.py
> +    password = models.CharField(
давай сюда добавим валидатор на специальные символы

2024-03-22 17:33 UTC, ZubritskiyAlex commented on autosalon/api/models.py
> +    counter_of_car = models.PositiveIntegerField(
не  очень идея хранить количество машин в автосалоне в отдельном столбце в БД. Подумай почему и какие проблемы могут быть в связи с этим))
поле давай уберем (количество машин принадлежащих автосалону можно высчитывать с помощью аннотирующего запроса)

2024-03-22 17:33 UTC, ZubritskiyAlex commented on autosalon/api/views.py
> +# Create your views here.
всю логику нужно покрывать тестами, для тестирования давай исползовать ААА подход и библиотеку ddf
django dynamic fixtures

2024-03-22 17:33 UTC, ZubritskiyAlex commented on autosalon/api/models.py
> +    is_active = models.BooleanField(
а зачем здесь is_active?
если я правильно понимаю, то это набор характеристик автомобиля, можно половину поле переписать используя enum или textchoices (посмотри например как здесь реализован поиск по параметрам 
)


https://cars.av.by/filter?utm_source=google&utm_medium=cpc&utm_campaign=leasing-poisk-brend&utm_content=adaptiv&utm_term=%D0%B0%D0%B2%20%D0%B1%D0%B0%D0%B9&gad_source=1&gclid=Cj0KCQjw2PSvBhDjARIsAKc2cgN906QBJcXmqKPnYHAkODLWOUl69MthJ7-kbLS1jtFsHIugh_xrQOwaAvfBEALw_wcB

2024-03-22 17:33 UTC, ZubritskiyAlex commented on autosalon/api/admin.py
> +# Register your models here.
Зарегистрируй модели в админке и настрой кастомную фильтрацию/поиск

2024-03-22 17:33 UTC, ZubritskiyAlex commented on autosalon/api/apps.py
> +class ApiConfig(AppConfig):
Давай еще настроим pre-commit и pre-push hooks, и настрой пожалуйста github actions таким образом, чтобы по пушу в любую из веток запускались линтеры и форматтеры 
https://www.youtube.com/watch?v=NijFSs03Pd4

2024-03-23 07:10 UTC, magelick commented on autosalon/users/models.py
> +    username = models.CharField(
Типо для того, чтобы разграничить на роли (админ, менеджер, покупатель) ?

2024-03-26 08:20 UTC, magelick commented
1. Изменил username в модели Customer;
2. Добавил проверку на специальные символы в password;
3. Убрал счётчик в модели AutoSalon (будут коореляции);
4. Написал тесты с использованием ddf;
5. Убрал is_active в модели OptionCar;
6. Зарегистрировал модели в админке;
7. Настроил pre-commit / github actions; 
При проверке на удалённом репозитории mypy не выдаёт ошибок, однако при push в удалённый, в action падает ошибка (error: Skipping analyzing "django_dynamic_fixture": module is installed, but missing library stubs or py.typed marker  [import-untyped]);

2024-03-27 08:07 UTC, ZubritskiyAlex approved these changes

2024-03-27 08:07 UTC, ZubritskiyAlex commented on .github/workflows/cheks.yml
> +      uses: actions/setup-python@v2
нужен v4 (почитай почему)

2024-03-27 08:07 UTC, ZubritskiyAlex commented on autosalon/api/migrations/0002_initial.py
> +                to="api.supplier", verbose_name="Suppliers of AutoSalon"
давай сделаем сквош 2 миграций

2024-03-27 08:07 UTC, ZubritskiyAlex commented on autosalon/api/tests.py
> +        self.assertTrue(isinstance(autosalon, AutoSalon))
Этот тест тестирует работу библиотеки ddf, а не твою логику, такой тест нам не нужен)

2024-03-27 11:07 UTC, merged