toolbar ans swagger
magelick/AutoSalon-trainee- pull request #5
Opened 2024-04-02 10:46 UTC by magelick

1. Установил и подключил swagger;
2. Немного прописал описание эндпоинтов и разбил их на тэги;
3. Прописал класс расширения для JWT-авторизации в swagger;
4. Установил и подключил toolbar;

2024-04-02 13:38 UTC, ZubritskiyAlex requested changes

2024-04-02 13:38 UTC, ZubritskiyAlex commented on autosalon/api/views.py
>      queryset = SpecialOfferOfAutoSalon.objects.select_related("dealer").all()
Давай на уровне моделей разместим все запросы 
вот пример
https://djangodoc.ru/3.2/topics/db/managers/#calling-custom-queryset-methods-from-the-manager

2024-04-02 13:38 UTC, ZubritskiyAlex commented on autosalon/api/views.py
>      queryset = SpecialOfferOfAutoSalon.objects.select_related("dealer").all()
И плюс давай любой новый функционал покрывать тестами с использованием ААА подхода, моков и параметризации. На селекторы также нужно написать тесты + в тесте проверять сколько запросов идет (assert_num_queries можно использовать)

2024-04-04 09:23 UTC, magelick commented
1. Написал тесты для эндпоинтов;
2. Прописал кастомных менеджеров для моделек;

2024-04-05 06:21 UTC, ZubritskiyAlex requested changes

2024-04-05 06:21 UTC, ZubritskiyAlex commented on autosalon/api/managers.py
> +        return self.filter(color="red")
здесь нужны ENUMы с цветами, типами кузова и тд

2024-04-05 06:21 UTC, ZubritskiyAlex commented on autosalon/users/tests/test_views.py
> +            "username": "manager",
это следует вынести в фикстуру

2024-04-05 06:21 UTC, ZubritskiyAlex commented on autosalon/users/tests/test_views.py
> +        data = {
фикстура

2024-04-05 06:21 UTC, ZubritskiyAlex commented on autosalon/users/tests/test_views.py
> +class CustomerTestCase(APITestCase):
для тестов используем pytest и ddf

2024-04-05 06:21 UTC, ZubritskiyAlex commented on autosalon/users/tests/test_views.py
> +        data = {
фикстура

2024-04-05 06:21 UTC, ZubritskiyAlex commented on autosalon/users/tests/test_views.py
> +        serializer_data = SaleHistoryOfCustomerSerializer(self.sale_history1).data
почитай правила нэйминга по PEP 8, либо sale_history_1, либо (и лучше) first_sale_history

2024-04-05 06:21 UTC, ZubritskiyAlex commented on autosalon/users/tests/test_views.py
> +        data1 = {
здесь можно 2 фикстуры или параметризацию

2024-04-05 06:21 UTC, ZubritskiyAlex commented on autosalon/users/tests/test_views.py
> +        data1 = {
pytest.parametrize

2024-04-05 11:55 UTC, magelick commented
Я исправил все вышесказанные замечания. 
Однако у меня возникла небольшая проблема с pytest. Установил, прописал pytest.ini в основной директории django-проекта (там де и где manage.py). При запуске pytest внутир контейнера (docker exec -it autosalon pytest) падает ошибка , что не нашёл настройки:  
django.core.exceptions.ImproperlyConfigured: Requested setting DDF_DEFAULT_DATA_FIXTURE, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

Гуглил, искал, но всё равно  не нашёл толком ответа. Может ты сталкивался с такой проблемой?

2024-04-05 16:04 UTC, ZubritskiyAlex approved these changes

2024-04-05 16:04 UTC, ZubritskiyAlex commented on autosalon/users/tests/test_views.py
> +            "refresh_token": create_refresh_token(sub=self.first_customer.id)
я говорил про фикстуры))) в некст тестах пишем фикстуры)

2024-04-06 06:13 UTC, merged